## **PHASE 1 PROJECT: AVIATION**
## <u>**Overview**</u>
We will use data cleaning, imputation, analysis, and visualization to generate insights for purchasing and operating airplanes.

## <u>**Business Problem**</u>
A company is expanding into new industries to diversify its portfolio. Specifically, they are interested in purchasing and operating airplanes for commercial and private enterprises but do not know anything about the potential risks of aircraft. You are charged with determining which aircraft are the lowest risk for the company to start this new business endeavor. You must then translate your findings into actionable insights that the head of the new aviation division can use to help decide which aircraft to purchase.

***Some of the business objectives we will focus on are:***
 - Try to give a brief understanding of the potential risks of aircraft.
 - Determining whether it is better purchasing and operating airplanes for commercial or private enterprises
 - Determining which aircraft are the lowest risk for the company when starting this new business endeavor.
 - Translate your findings into actionable insights that the head of the new aviation division can use to help decide which aircraft to    purchase.

## <u>**Data**</u>
The dataset used is from the National Transportation Safety Board which includes aviation accident data from 1962 to 2023 about civil aviation accidents and selected incidents in the United States and international waters.

## <u>Data Understanding/EDA</u>

##### Importing Libraries

In [22]:
import pandas as pd
import numpy as np

##### Load Data(Encoding)

In [6]:
df = pd.read_csv("AviationData.csv", encoding="latin1", low_memory=False)
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [7]:
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

##### Summary Statistics

In [11]:
#Getting insight on no of rows and columns,data types and null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [13]:
# Understanding data by the mean count of columns that have values
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

In [16]:
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

##### Data Cleaning/Preparation
We will check for missing values, handle missing values, check for duplicates, and data type conversion

In [24]:
#Checking if the Event ID has duplicates
df["Event.Id"].duplicated().value_counts()

Event.Id
False    87951
True       938
Name: count, dtype: int64

In [28]:
# Checking if the duplicate event.id is the same accident
df[df["Event.Id"].duplicated(keep=False)]

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
117,20020917X01908,Accident,DCA82AA012B,1982-01-19,"ROCKPORT, TX",United States,NaN,NaN,RKP,ARANSAS COUNTY AIRPORT,...,Personal,NaN,3.0,0.0,0.0,0.0,IMC,Approach,Probable Cause,19-01-1983
118,20020917X01908,Accident,DCA82AA012A,1982-01-19,"ROCKPORT, TX",United States,NaN,NaN,RKP,ARANSAS COUNTY AIRPORT,...,Executive/corporate,NaN,3.0,0.0,0.0,0.0,IMC,Approach,Probable Cause,19-01-1983
153,20020917X02259,Accident,LAX82FA049A,1982-01-23,"VICTORVILLE, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,4.0,0.0,VMC,Unknown,Probable Cause,23-01-1983
158,20020917X02400,Accident,MIA82FA038B,1982-01-23,"NEWPORT RICHEY, FL",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,3.0,VMC,Cruise,Probable Cause,23-01-1983
159,20020917X02400,Accident,MIA82FA038A,1982-01-23,"NEWPORT RICHEY, FL",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,3.0,VMC,Approach,Probable Cause,23-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88796,20221121106336,Accident,WPR23LA041,2022-11-18,"Las Vegas, NV",United States,361239N,1151140W,VGT,NORTH LAS VEGAS,...,Instructional,702 HELICOPTER INC,0.0,0.0,0.0,3.0,VMC,NaN,NaN,07-12-2022
88797,20221122106340,Incident,DCA23WA071,2022-11-18,"Marrakech,",Morocco,NaN,NaN,NaN,NaN,...,NaN,British Airways,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88798,20221122106340,Incident,DCA23WA071,2022-11-18,"Marrakech,",Morocco,NaN,NaN,NaN,NaN,...,NaN,Valair Private Jets,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88813,20221123106354,Accident,WPR23LA045,2022-11-22,"San Diego, CA",United States,323414N,1165825W,SDM,Brown Field Municipal Airport,...,Instructional,HeliStream Inc.,0.0,0.0,0.0,4.0,VMC,NaN,NaN,22-12-2022
88814,20221123106354,Accident,WPR23LA045,2022-11-22,"San Diego, CA",United States,323414N,1165825W,SDM,Brown Field Municipal Airport,...,Public Aircraft - Federal,U.S. Navy,0.0,0.0,0.0,4.0,VMC,NaN,NaN,22-12-2022

In [30]:
# Understanding the duplicate with a less data
df[df["Event.Id"].duplicated(keep=False)].head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
117,20020917X01908,Accident,DCA82AA012B,1982-01-19,"ROCKPORT, TX",United States,NaN,NaN,RKP,ARANSAS COUNTY AIRPORT,...,Personal,NaN,3.0,0.0,0.0,0.0,IMC,Approach,Probable Cause,19-01-1983
118,20020917X01908,Accident,DCA82AA012A,1982-01-19,"ROCKPORT, TX",United States,NaN,NaN,RKP,ARANSAS COUNTY AIRPORT,...,Executive/corporate,NaN,3.0,0.0,0.0,0.0,IMC,Approach,Probable Cause,19-01-1983
153,20020917X02259,Accident,LAX82FA049A,1982-01-23,"VICTORVILLE, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,4.0,0.0,VMC,Unknown,Probable Cause,23-01-1983
158,20020917X02400,Accident,MIA82FA038B,1982-01-23,"NEWPORT RICHEY, FL",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,3.0,VMC,Cruise,Probable Cause,23-01-1983
159,20020917X02400,Accident,MIA82FA038A,1982-01-23,"NEWPORT RICHEY, FL",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,3.0,VMC,Approach,Probable Cause,23-01-1983

###### Assumption
From the above df the Event.id has duplicates but in the rows duplicated there is a slight change in the Accident.Number, Purpose.of.flight or Broad.phase.of.flight.
Therefore I asssumed in the event there might have been two accidents with two aircraft

In [32]:
# Confirming our assumption by using accident no as a key
df[df["Accident.Number"].duplicated(keep=False)]

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
87304,20220111104514,Accident,ERA22LA103,2022-01-08,"Knoxville, TN",United States,355750N,0835225W,DKX,KNOXVILLE DOWNTOWN ISLAND,...,Personal,NaN,0.0,0.0,0.0,4.0,VMC,NaN,The pilot of the Cessna 150s failure to avoid...,14-06-2022
87305,20220111104514,Accident,ERA22LA103,2022-01-08,"Knoxville, TN",United States,355750N,0835225W,DKX,KNOXVILLE DOWNTOWN ISLAND,...,Personal,NaN,0.0,0.0,0.0,4.0,VMC,NaN,The pilot of the Cessna 150s failure to avoid...,14-06-2022
87330,20220309104747,Incident,DCA22WA089,2022-01-15,"Sukkur, OF",Pakistan,NaN,NaN,NaN,NaN,...,NaN,Air Arabia,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
87331,20220309104747,Incident,DCA22WA089,2022-01-15,"Sukkur, OF",Pakistan,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
87347,20220801105632,Incident,DCA22WA167,2022-01-22,"Kigali,",Rwanda,001587S,0030822E,NaN,NaN,...,NaN,RwandAir,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
87348,20220801105632,Incident,DCA22WA167,2022-01-22,"Kigali,",Rwanda,001587S,0030822E,NaN,NaN,...,NaN,Ethopian Air,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
87411,20220212104630,Accident,ERA22LA119,2022-02-11,"Naples, FL",United States,026930N,0081464W,APF,NAPLES MUNI,...,Personal,Tatann Aviation Inc.,0.0,0.0,0.0,2.0,VMC,NaN,"The biplane pilots inadequate visual lookout,...",22-09-2022
87412,20220212104630,Accident,ERA22LA119,2022-02-11,"Naples, FL",United States,026930N,0081464W,APF,NAPLES MUNI,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,"The biplane pilots inadequate visual lookout,...",22-09-2022
87548,20220323104818,Accident,CEN22LA149,2022-03-18,"Grapevine, TX",United States,032530N,0097251W,DFW,Dallas Ft. Worth,...,Business,MARTINAIRE AVIATION LLC,0.0,0.0,0.0,2.0,VMC,NaN,The failure of the pilot of the second aircraf...,05-07-2022
87549,20220323104818,Accident,CEN22LA149,2022-03-18,"Grapevine, TX",United States,032530N,0097251W,DFW,Dallas Ft. Worth,...,Business,MARTINAIRE AVIATION LLC,0.0,0.0,0.0,2.0,VMC,NaN,The failure of the pilot of the second aircraf...,05-07-2022
87622,20220406104897,Accident,WPR22LA143,2022-04-02,"Van Nuys, CA",United States,034137N,1182932W,VNY,Van Nuys,...,Executive/corporate,SANCTUS AVIATION LLC,0.0,0.0,0.0,8.0,VMC,NaN,The student pilots failure to maintain suffic...,20-07-2022
87623,20220406104897,Accident,WPR22LA143,2022-04-02,"Van Nuys, CA",United States,034137N,1182932W,VNY,Van Nuys,...,Instructional,NaN,0.0,0.0,0.0,8.0,VMC,NaN,The student pilots failure to maintain suffic...,20-07-2022
87916,20220614105258,Incident,DCA22WA130,2022-06-05,"Peshawar, OF",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
87917,20220614105258,Incident,DCA22WA130,2022-06-05,"Peshawar, OF",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
87931,20220608105217,Accident,WPR22LA201,2022-06-07,"Hawthorne, CA",United States,335520N,0118203W,KHHR,Jack Northrop Field/Hawthorne,...,Business,Western Aircraft Inc.,0.0,0.0,0.0,11.0,VMC,NaN,The multi-engine pilot's failure to maintain c...,02-12-2022
87932,20220608105217,Accident,WPR22LA201,2022-06-07,"Hawthorne, CA",United States,335520N,0118203W,KHHR,Jack Northrop Field/Hawthorne,...,Business,PACIFIC DENTAL SERVICES LLC,0.0,0.0,0.0,11.0,VMC,NaN,The multi-engine pilot's failure to maintain c...,02-12-2022
87990,20220623105317,Accident,DCA22LA135,2022-06-18,"New York, NY",United States,403833N,0734644W,KJFK,John F kennedy International,...,NaN,ITALIA TRASPORTO AEREO SPA(ITA Airways),0.0,0.0,0.0,0.0,VMC,NaN,NaN,NaN
87991,20220623105317,Accident,DCA22LA135,2022-06-18,"New York, NY",United States,403833N,0734644W,KJFK,John F kennedy International,...,NaN,Air France,0.0,0.0,0.0,0.0,VMC,NaN,NaN,NaN
88084,20220726105577,Incident,DCA22WA158,2022-07-02,"Barcelona,",Spain,411750N,0002442E,LEBL,Barcelona International Airpor,...,NaN,DELTA AIR LINES INC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88085,20220726105577,Incident,DCA22WA158,2022-07-02,"Barcelona,",Spain,411750N,0002442E,LEBL,Barcelona International Airpor,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88095,20220804105661,Incident,DCA22WA172,2022-07-04,"TBD,",MU,NaN,NaN,NaN,NaN,...,NaN,Omani Airlines,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88096,20220804105661,Incident,DCA22WA172,2022-07-04,"TBD,",MU,NaN,NaN,NaN,NaN,...,NaN,Saudi Airlines,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88167,20220802105640,Accident,GAA22WA241,2022-07-16,"Aaachen,",Georgia,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88168,20220802105640,Accident,GAA22WA241,2022-07-16,"Aaachen,",Georgia,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88174,20220718105496,Accident,ERA22FA318,2022-07-17,"Las Vegas, NV",United States,361239N,1151140W,VGT,NORTH LAS VEGAS,...,Personal,NaN,4.0,0.0,0.0,0.0,VMC,NaN,NaN,05-08-2022
88175,20220718105496,Accident,ERA22FA318,2022-07-17,"Las Vegas, NV",United States,361239N,1151140W,VGT,NORTH LAS VEGAS,...,Instructional,Airwork Las Vegas,4.0,0.0,0.0,0.0,VMC,NaN,NaN,05-08-2022
88240,20220727105589,Accident,ERA22FA338,2022-07-26,"Portland, AR",United States,331336N,0912816W,NaN,NaN,...,Aerial Application,WESTWIND AIR LLC,1.0,0.0,1.0,0.0,VMC,NaN,NaN,18-08-2022
88241,20220727105589,Accident,ERA22FA338,2022-07-26,"Portland, AR",United States,331336N,0912816W,NaN,NaN,...,Aerial Application,LASSCO LLC,1.0,0.0,1.0,0.0,VMC,NaN,NaN,18-08-2022
88257,20220730105623,Accident,CEN22LA346,2022-07-28,"Oshkosh, WI",United States,043599N,0883329W,OSH,Wittman Regional,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The failure of the pilot of N694V (RV-8) to ma...,22-09-2022
88258,20220730105623,Accident,CEN22LA346,2022-07-28,"Oshkosh, WI",United States,043599N,0883329W,OSH,Wittman Regional,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,The failure of the pilot of N694V (RV-8) to ma...,22-09-2022
88314,20220808105682,Accident,ERA22LA364,2022-08-06,"Erwinna, PA",United States,040293N,0075559W,9N1,VANSANT,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,NaN,19-09-2022
88315,20220808105682,Accident,ERA22LA364,2022-08-06,"Erwinna, PA",United States,040293N,0075559W,9N1,VANSANT,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,NaN,NaN,19-09-2022
88371,20220818105763,Accident,WPR22FA309,2022-08-18,"Watsonville, CA",United States,365623N,1214715W,WVI,WATSONVILLE MUNI,...,Personal,United Flight Services,3.0,0.0,0.0,0.0,NaN,NaN,NaN,15-09-2022
88372,20220818105763,Accident,WPR22FA309,2022-08-18,"Watsonville, CA",United States,365623N,1214715W,WVI,WATSONVILLE MUNI,...,Personal,NaN,3.0,0.0,0.0,0.0,NaN,NaN,NaN,15-09-2022
88386,20220822105776,Accident,ERA22LA379,2022-08-20,"Bealeton, VA",United States,038338N,0774255W,3VA3,Flying Circus Aerodrome,...,Business,NaN,0.0,2.0,0.0,2.0,VMC,NaN,NaN,27-09-2022
88387,20220822105776,Accident,ERA22LA379,2022-08-20,"Bealeton, VA",United States,038338N,0774255W,3VA3,Flying Circus Aerodrome,...,Business,NaN,0.0,2.0,0.0,2.0,VMC,NaN,NaN,27-09-2022
88512,20220915105950,Accident,DCA22LA201,2022-09-11,"Chicago, IL",United States,NaN,NaN,NaN,NaN,...,NaN,American Airlines,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88513,20220915105950,Accident,DCA22LA201,2022-09-11,"Chicago, IL",United States,NaN,NaN,NaN,NaN,...,NaN,SOUTHWEST AIRLINES CO,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88527,20220921105978,Incident,DCA22WA204,2022-09-14,"Mumbai,",India,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88528,20220921105978,Incident,DCA22WA204,2022-09-14,"Mumbai,",India,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88537,20220918105957,Accident,CEN22FA424,2022-09-17,"Longmont, CO",United States,040619N,0105721W,NaN,NaN,...,Personal,NaN,3.0,0.0,0.0,0.0,VMC,NaN,NaN,07-10-2022
88538,20220918105957,Accident,CEN22FA424,2022-09-17,"Longmont, CO",United States,040619N,0105721W,NaN,NaN,...,Instructional,McAir Aviation,3.0,0.0,0.0,0.0,VMC,NaN,NaN,07-10-2022
88592,20220929106019,Accident,DCA22WA214,2022-09-28,"London,",Great Britain,512820N,0002717E,EGLL,London Heathrow Airport,...,NaN,NaN,0.0,0.0,0.0,2.0,NaN,NaN,NaN,12-10-2022
88593,20220929106019,Accident,DCA22WA214,2022-09-28,"London,",Great Britain,512820N,0002717E,EGLL,London Heathrow Airport,...,NaN,NaN,0.0,0.0,0.0,2.0,NaN,NaN,NaN,NaN
88776,20221112106276,Accident,CEN23MA034,2022-11-12,"Dallas, TX",United States,324026N,0965146W,RBD,Dallas Executive,...,ASHO,Commemorative Air Force,6.0,0.0,0.0,0.0,VMC,NaN,NaN,30-11-2022
88777,20221112106276,Accident,CEN23MA034,2022-11-12,"Dallas, TX",United States,324026N,0965146W,RBD,Dallas Executive,...,ASHO,Commemorative Air Force,6.0,0.0,0.0,0.0,VMC,NaN,NaN,30-11-2022
88795,20221121106336,Accident,WPR23LA041,2022-11-18,"Las Vegas, NV",United States,361239N,1151140W,VGT,NORTH LAS VEGAS,...,Instructional,SOUTHERN UTAH UNIVERSITY,0.0,0.0,0.0,3.0,VMC,NaN,NaN,07-12-2022
88796,20221121106336,Accident,WPR23LA041,2022-11-18,"Las Vegas, NV",United States,361239N,1151140W,VGT,NORTH LAS VEGAS,...,Instructional,702 HELICOPTER INC,0.0,0.0,0.0,3.0,VMC,NaN,NaN,07-12-2022
88797,20221122106340,Incident,DCA23WA071,2022-11-18,"Marrakech,",Morocco,NaN,NaN,NaN,NaN,...,NaN,British Airways,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88798,20221122106340,Incident,DCA23WA071,2022-11-18,"Marrakech,",Morocco,NaN,NaN,NaN,NaN,...,NaN,Valair Private Jets,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88813,20221123106354,Accident,WPR23LA045,2022-11-22,"San Diego, CA",United States,323414N,1165825W,SDM,Brown Field Municipal Airport,...,Instructional,HeliStream Inc.,0.0,0.0,0.0,4.0,VMC,NaN,NaN,22-12-2022
88814,20221123106354,Accident,WPR23LA045,2022-11-22,"San Diego, CA",United States,323414N,1165825W,SDM,Brown Field Municipal Airport,...,Public Aircraft - Federal,U.S. Navy,0.0,0.0,0.0,4.0,VMC,NaN,NaN,22-12-2022

##### Dealing with Missing Values
We will look at columns with missing values and determine what we will do.

In [33]:
#Checking for missing data in columns
df.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

###### **Assumption**
We will assume that the categorical data for the missing values cannot be found is therefore less relevant
We will work with numerical data eg Total Fatal Injuries, Total Serious Injuries, Total Uninjured

###### **Filter Relevant Columns**
It is easier to deal with the missing marks of the relevant columns

In [75]:
relevant_columns = [
    "Event.Date", "Location", "Country", "Injury.Severity", "Aircraft.damage", 
    "Make", "Model", "Number.of.Engines", "Engine.Type", "Purpose.of.flight", 
    "Total.Fatal.Injuries", "Total.Serious.Injuries", "Total.Minor.Injuries", 
    "Total.Uninjured", "Weather.Condition", "Broad.phase.of.flight"
]

filtered_df = df.filter(items=relevant_columns).copy()
filtered_df

,Event.Date,Location,Country,Injury.Severity,Aircraft.damage,Make,Model,Number.of.Engines,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight
0,1948-10-24,"MOOSE CREEK, ID",United States,Fatal(2),Destroyed,Stinson,108-3,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,UNK,Cruise
1,1962-07-19,"BRIDGEPORT, CA",United States,Fatal(4),Destroyed,Piper,PA24-180,1.0,Reciprocating,Personal,4.0,0.0,0.0,0.0,UNK,Unknown
2,1974-08-30,"Saltville, VA",United States,Fatal(3),Destroyed,Cessna,172M,1.0,Reciprocating,Personal,3.0,NaN,NaN,NaN,IMC,Cruise
3,1977-06-19,"EUREKA, CA",United States,Fatal(2),Destroyed,Rockwell,112,1.0,Reciprocating,Personal,2.0,0.0,0.0,0.0,IMC,Cruise
4,1979-08-02,"Canton, OH",United States,Fatal(1),Destroyed,Cessna,501,NaN,NaN,Personal,1.0,2.0,NaN,0.0,VMC,Approach
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,2022-12-26,"Annapolis, MD",United States,Minor,NaN,PIPER,PA-28-151,NaN,NaN,Personal,0.0,1.0,0.0,0.0,NaN,NaN
88885,2022-12-26,"Hampton, NH",United States,NaN,NaN,BELLANCA,7ECA,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN
88886,2022-12-26,"Payson, AZ",United States,Non-Fatal,Substantial,AMERICAN CHAMPION AIRCRAFT,8GCBC,1.0,NaN,Personal,0.0,0.0,0.0,1.0,VMC,NaN
88887,2022-12-26,"Morgan, UT",United States,NaN,NaN,CESSNA,210N,NaN,NaN,Personal,0.0,0.0,0.0,0.0,NaN,NaN
88888,2022-12-29,"Athens, GA",United States,Minor,NaN,PIPER,PA-24-260,NaN,NaN,Personal,0.0,1.0,0.0,1.0,NaN,NaN

In [76]:
# Replace Total.Fatal.Injuries	Total.Serious.Injuries	Total.Minor.Injuries	Total.Uninjured	 missing values with 0's
filtered_df[["Total.Fatal.Injuries", "Total.Serious.Injuries", "Total.Minor.Injuries", "Total.Uninjured"]] = (
    filtered_df[["Total.Fatal.Injuries", "Total.Serious.Injuries", "Total.Minor.Injuries", "Total.Uninjured"]].fillna(0)
)

In [77]:
#Checking if null values in Total.Fatal.Injuries Total.Serious.Injuries	Total.Minor.Injuries Total.Uninjured are replaced
filtered_df[["Total.Fatal.Injuries", "Total.Serious.Injuries", "Total.Minor.Injuries", "Total.Uninjured"]].isna().sum()

Total.Fatal.Injuries      0
Total.Serious.Injuries    0
Total.Minor.Injuries      0
Total.Uninjured           0
dtype: int64

In [85]:
# Replace Number.of.Engines with 1's
filtered_df["Number.of.Engines"] = filtered_df["Number.of.Engines"].fillna(1)

In [86]:
#Checking if null values in 
filtered_df[["Number.of.Engines"]].isna().sum()

Number.of.Engines    0
dtype: int64